In [1]:
import pandas as pd

titanic_url = 'https://raw.githubusercontent.com/PinkWink/ML_tutorial'+\
                                    '/master/dataset/titanic.xls'
titanic = pd.read_excel(titanic_url)
titanic.head()

pclass  survived  ...   body                        home.dest
0       1         1  ...    NaN                     St Louis, MO
1       1         1  ...    NaN  Montreal, PQ / Chesterville, ON
2       1         0  ...    NaN  Montreal, PQ / Chesterville, ON
3       1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4       1         0  ...    NaN  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

In [2]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(titanic['sex'])
titanic['gender'] = le.transform(titanic['sex'])
titanic.head()

pclass  survived  ...                        home.dest gender
0       1         1  ...                     St Louis, MO      0
1       1         1  ...  Montreal, PQ / Chesterville, ON      1
2       1         0  ...  Montreal, PQ / Chesterville, ON      0
3       1         0  ...  Montreal, PQ / Chesterville, ON      1
4       1         0  ...  Montreal, PQ / Chesterville, ON      0

[5 rows x 15 columns]

In [3]:
titanic = titanic[titanic['age'].notnull()]
titanic = titanic[titanic['fare'].notnull()]
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1045 entries, 0 to 1308
Data columns (total 15 columns):
pclass       1045 non-null int64
survived     1045 non-null int64
name         1045 non-null object
sex          1045 non-null object
age          1045 non-null float64
sibsp        1045 non-null int64
parch        1045 non-null int64
ticket       1045 non-null object
fare         1045 non-null float64
cabin        272 non-null object
embarked     1043 non-null object
boat         417 non-null object
body         119 non-null float64
home.dest    685 non-null object
gender       1045 non-null int64
dtypes: float64(3), int64(5), object(7)
memory usage: 130.6+ KB


In [0]:
y = titanic['survived'].values
X = titanic[['pclass','age','sibsp','parch','fare','gender']].values

In [0]:
from sklearn.preprocessing import StandardScaler

SS = StandardScaler()
SS.fit(X)

X_ss = SS.transform(X)

In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold

log_reg_kf = LogisticRegression(random_state=13, solver='liblinear')
kfold = KFold(n_splits=5)
cv_accuracy = []

In [0]:
from sklearn.metrics import accuracy_score

for train_idx, test_idx in kfold.split(X_ss):
    X_train, X_test = X_ss[train_idx], X_ss[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    log_reg_kf.fit(X_train, y_train)
    
    pred = log_reg_kf.predict(X_test)
    accuracy = accuracy_score(y_test, pred)

    cv_accuracy.append(accuracy)

In [8]:
cv_accuracy

[0.7655502392344498,
 0.8660287081339713,
 0.8229665071770335,
 0.7464114832535885,
 0.7081339712918661]

In [9]:
import numpy as np

np.mean(cv_accuracy)

0.7818181818181819

In [10]:
for train_idx, test_idx in kfold.split(X_ss):
    X_train, X_test = X_ss[train_idx], X_ss[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    print(np.unique(y_test, return_counts=True))

(array([0, 1]), array([ 74, 135]))
(array([0, 1]), array([107, 102]))
(array([0, 1]), array([125,  84]))
(array([0, 1]), array([155,  54]))
(array([0, 1]), array([157,  52]))


In [0]:
from sklearn.model_selection import StratifiedKFold

log_reg_kf = LogisticRegression(random_state=13, solver='liblinear')
skfold = StratifiedKFold(n_splits=5)
cv_accuracy = []

In [12]:
for train_idx, test_idx in skfold.split(X_ss, y):
    X_train, X_test = X_ss[train_idx], X_ss[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    print(np.unique(y_test, return_counts=True))

(array([0, 1]), array([124,  86]))
(array([0, 1]), array([124,  86]))
(array([0, 1]), array([124,  85]))
(array([0, 1]), array([123,  85]))
(array([0, 1]), array([123,  85]))


In [0]:
for train_idx, test_idx in skfold.split(X_ss, y):
    X_train, X_test = X_ss[train_idx], X_ss[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    log_reg_kf.fit(X_train, y_train)
    
    pred = log_reg_kf.predict(X_test)
    accuracy = accuracy_score(y_test, pred)

    cv_accuracy.append(accuracy)

In [14]:
cv_accuracy

[0.5666666666666667,
 0.8666666666666667,
 0.8086124401913876,
 0.7403846153846154,
 0.6538461538461539]

In [15]:
np.mean(cv_accuracy)

0.7272353085510981

In [0]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(log_reg_kf, X_ss, y, scoring='accuracy', cv=5)

In [17]:
scores

array([0.56666667, 0.86666667, 0.80861244, 0.74038462, 0.65384615])

In [18]:
np.mean(scores)

0.7272353085510981

In [0]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()

In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = \
                        train_test_split(X, y, test_size=0.2, random_state=13)

In [0]:
from sklearn.model_selection import GridSearchCV

parameters = {'max_depth':[2, 3, 4, 5], 'min_samples_split':[2, 3, 4]}
grid_clf = GridSearchCV(clf, param_grid = parameters, cv=3)

In [22]:
grid_clf.fit(X_train, y_train)

GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=None,
             param_grid={'max_depth': [2, 3, 4, 5],
                         'min_samples_split': [2, 3, 4]},
             pre_dispatch=

In [23]:
scores_df = pd.DataFrame(grid_clf.cv_results_)
scores_df[['rank_test_score', 'params', 'mean_test_score', 'split0_test_score', 
           'split1_test_score', 'split2_test_score']]

rank_test_score  ... split2_test_score
0                10  ...          0.794964
1                10  ...          0.794964
2                10  ...          0.794964
3                 4  ...          0.805755
4                 4  ...          0.805755
5                 4  ...          0.805755
6                 2  ...          0.805755
7                 2  ...          0.805755
8                 1  ...          0.805755
9                 9  ...          0.798561
10                7  ...          0.802158
11                7  ...          0.802158

[12 rows x 6 columns]

In [24]:
grid_clf.best_params_

{'max_depth': 4, 'min_samples_split': 4}

In [25]:
grid_clf.best_score_

0.8038277511961722

In [26]:
clf_best = grid_clf.best_estimator_

pred = clf_best.predict(X_test)
accuracy_score(y_test, pred)

0.7655502392344498